### ISSUE TITLE
r2 pipe unable to fetch

### ISSUE THREAD

**Issue by abhyuday07** [radare/radare2-r2pipe#102]
r2-pipe is unable to fetch output and crashes with the following message.

```
Traceback (most recent call last):
  File "Hash_helper.py", line 167, in <module>
    temp = preprocess_files(sys.argv[1])
  File "Hash_helper.py", line 45, in preprocess_files
    print(bf.cmdj(cmd_str))
  File "/home/abhyuday/.local/lib/python3.6/site-packages/r2pipe/open_base.py", line 216, in cmdj
    result = self.cmd(cmd, **kwargs)
  File "/home/abhyuday/.local/lib/python3.6/site-packages/r2pipe/open_base.py", line 204, in cmd
    res = self._cmd(cmd, **kwargs)
  File "/home/abhyuday/.local/lib/python3.6/site-packages/r2pipe/open_sync.py", line 102, in _cmd_process
    self.process.stdin.write((cmd + '\n').encode('utf8'))
AttributeError: 'open' object has no attribute 'process'
```

**Comment by radare** [comment]
?

**Comment by abhyuday07** [comment]
I figured out the problem
