### ISSUE TITLE
Install error on Window 10

### ISSUE THREAD

**Issue by harjot-oberai** [radare/radare2-r2pipe#49]
I am trying to install r2pipe on windows 10, 64 bit, but it always fails with the following error
```
H:\PythonProjects\abdb_patcher>pip install r2pipe
Collecting r2pipe
  Using cached r2pipe-0.9.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\harjot\appdata\local\temp\pip-build-qqhd4v\r2pipe\setup.py", line 2, in <module>
        import r2pipe
      File "r2pipe\__init__.py", line 45, in <module>
        from .native import RCore
      File "r2pipe\native.py", line 9, in <module>
        lib = WinDLL(find_library('r_core'))
      File "c:\python27\lib\ctypes\__init__.py", line 362, in __init__
        self._handle = _dlopen(self._name, mode)
    TypeError: expected string or Unicode object, NoneType found

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\harjot\appdata\local\temp\pip-build-qqhd4v\r2pipe\
```

**Comment by radare** [comment]
pls confirm if fixed in 0.9.9

**Comment by harjot-oberai** [comment]
Yup, fixed.

Thank you

**Comment by radare** [comment]
Awesome . Thanks for testing. Love blindfixes
