### ISSUE TITLE
TypeError on python3 when calling r2.quit()

### ISSUE THREAD

**Issue by epinna** [radare/radare2-r2pipe#57]
Hello,

Installed versions:

```
$ radare2 -v
radare2 2.5.0-git 17803 @ linux-x86-32 git.2.4.0-282-g43af9e3bb
commit: 43af9e3bb2ac50cd755d0ee89aca33bd3607e0ff build: 2018-04-06__15:17:12
$ pip freeze | grep r2pipe
r2pipe==0.9.9
$ pip3 freeze | grep r2pipe
r2pipe==0.9.9
```

R2-pipe test file `test.py`:

```
import r2pipe
r2 = r2pipe.open()
r2.quit()
```

It works if called with python2, but it breaks if called with python3 (both installed with pip and pip3):

```
$ radare2 /bin/ls
[0x00003dad]> #!pipe python2 ./test.py
[0x00003dad]> #!pipe python3 ./test.py
Traceback (most recent call last):
  File "./test.py", line 3, in <module>
    r2.quit()
  File "/usr/local/lib/python3.6/dist-packages/r2pipe/__init__.py", line 260, in quit
    self.cmd("q")
  File "/usr/local/lib/python3.6/dist-packages/r2pipe/__init__.py", line 274, in cmd
    res = self._cmd(cmd)
  File "/usr/local/lib/python3.6/dist-packages/r2pipe/__init__.py", line 214, in _cmd_pipe
    os.write(self.pipe[1], cmd)
TypeError: a bytes-like object is required, not 'str'
```

**Comment by a1ext** [comment]
Hi @epinna, could you re-check the issue with 1.1.0 version?

**Comment by a1ext** [comment]
Ok, closing the issue due to lack of feedback. Feel free to reopen it if you think the issue isn't solved
