### ISSUE TITLE
Python3 Script "a bytes-like object is required"

### ISSUE THREAD

**Issue by chase1635321** [radare/radare2-r2pipe#79]
I hope I'm not doing something wrong. 
It works fine when running the script on its own, but fails if run with r2 -i <script> <executable>. This issues appears to be similar to #64 and #57 but I can't figure out how to implement the fix.

Versions
```
$ radare2 -v
radare2 3.1.0-git 20082 @ linux-x86-64 git.3.0.1-273-g6d0f9ce
commit: 6d0f9ce282926af91d1350acaf4722a56a0467b0 build: 2018-11-18__13:29:11
$ pip freeze | grep r2pipe
r2pipe==0.9.9
```
Python3 script
```
$ cat r2.py 
import r2pipe
r = r2pipe.open()
r.cmd('aaa')
```
Running the script
```
$ r2 -i r2.py test.x 
Traceback (most recent call last):
  File "r2.py", line 4, in <module>
    r.cmd('aaa')
  File "/home/ck/.local/lib/python3.5/site-packages/r2pipe/__init__.py", line 274, in cmd
    res = self._cmd(cmd)
  File "/home/ck/.local/lib/python3.5/site-packages/r2pipe/__init__.py", line 214, in _cmd_pipe
    os.write(self.pipe[1], cmd)
TypeError: a bytes-like object is required, not 'str'
 -- Use zoom.byte=entropy and press 'z' in visual mode to zoom out to see the entropy of the whole file
[0x004004c0]> 
```

**Comment by a1ext** [comment]
I think it is solved, feel free to reopen an issue otherwise
