### ISSUE TITLE
Windows r2pipe + python asyncio issues

### ISSUE THREAD

**Issue by securitykitten** [radare/radare2-r2pipe#81]
I hope I'm doing this right, but there seems to be an issue when running r2pipe on Windows.  I have a clean Win7 (x64) install with python 2 & python 3 installed.  

#### Radare2 Version
```
PS C:\Users\admin> radare2 -v
radare2 3.1.0 1 @ windows-x86-64 git.3.1.0
commit: 0743c84ac3f1477439ab2aa54d7005eaa50dcd7e build: Mon 11/26/2018__ 3:08:07.27
```
#### r2pipe version (for python 2/3)
```
PS C:\Users\admin> pip2 show r2pipe
Name: r2pipe
Version: 1.0.0
Summary: Pipe interface for radare2
Home-page: http://rada.re
Author: pancake
Author-email: pancake@nopcode.org
License: MIT
Location: c:\python27\lib\site-packages
Requires:
Required-by:

PS C:\Users\admin> pip3 show r2pipe
Name: r2pipe
Version: 1.0.0
Summary: Pipe interface for radare2
Home-page: http://rada.re
Author: pancake
Author-email: pancake@nopcode.org
License: MIT
Location: c:\python37\lib\site-packages
Requires:
Required-by:
```
#### Creating the bug
When running in Python3
```
PS C:\Users\admin> python
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import r2pipe
>>> r = r2pipe.open('c:\windows\system32\calc.exe')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\r2pipe\open_async.py", line 34, in __init__
    watcher = asyncio.get_child_watcher()
  File "C:\Python37\lib\asyncio\events.py", line 767, in get_child_watcher
    return get_event_loop_policy().get_child_watcher()
  File "C:\Python37\lib\asyncio\events.py", line 603, in get_child_watcher
    raise NotImplementedError
NotImplementedError
```

When running in Python2
```
PS C:\Users\admin> C:\Python27\python.exe
Python 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import r2pipe
>>> r = r2pipe.open('c:\windows\system32\calc.exe')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\r2pipe\open_sync.py", line 52, in __init__
    fl = fcntl.fcntl(fd, fcntl.F_GETFL)
AttributeError: 'NoneType' object has no attribute 'fcntl'
```

I confirmed that I could open a binary using R2, so the issue seem to exist in `r2pipe.open()` only.

**Comment by radare** [comment]
Looks like a windows specific issue

**Comment by radare** [comment]
so the status of this is:

py3: fails everywhere
py2: fails only on windows

is this correct?

**Comment by securitykitten** [comment]
This issue was only relating to r2pipe's use on Windows, but I'm happy to check on a Linux build.

The TL;DR is what you said.

py3: fails everywhere
py2: fails only on windows.

Running on Ubuntu 18.04.1 LTS

### R2 Version
```
radare2 3.1.2 20314 @ linux-x86-64 git.3.1.2-11-g9e20fe9bb
commit: 9e20fe9bbb0df5cb2e1559c5429818391a9901c1 build: 2018-12-04__11:47:53
```

### Python3 r2pipe Information
```
pip3 show r2pipe
Name: r2pipe
Version: 1.0.0
Summary: Pipe interface for radare2
Home-page: http://rada.re
Author: pancake
Author-email: pancake@nopcode.org
License: MIT
Location: /usr/local/lib/python3.6/dist-packages
Requires: 
```

### Pip2 r2pipe information
```
pip2 show r2pipe
Name: r2pipe
Version: 1.0.0
Summary: Pipe interface for radare2
Home-page: http://rada.re
Author: pancake
Author-email: pancake@nopcode.org
License: MIT
Location: /usr/local/lib/python2.7/dist-packages
Requires: 
```

### Running in Python3
When running in python3, no results were returned with running `afl`
```
$ python3
Python 3.6.7 (default, Oct 22 2018, 11:32:17) 
[GCC 8.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import r2pipe
>>> r = r2pipe.open('/bin/ls')
>>> r.cmd('aa')
Invalid instruction of 16207 bytes at 0xf8
Invalid instruction of 16322 bytes at 0x40
<Task finished coro=<open._cmd_process() done, defined at /usr/local/lib/python3.6/dist-packages/r2pipe/open_async.py:95> result=''>
>>> r.cmd('afl')
<Task finished coro=<open._cmd_process() done, defined at /usr/local/lib/python3.6/dist-packages/r2pipe/open_async.py:95> result=''>
```

### Running in Python2
When running in python2 things seem to work as expected.
```
$ python2
Python 2.7.15rc1 (default, Nov 12 2018, 14:31:15) 
[GCC 7.3.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import r2pipe
>>> r = r2pipe.open('/bin/ls')
>>> r.cmd('aa')
Invalid instruction of 16207 bytes at 0xf8
Invalid instruction of 16322 bytes at 0x40
''
>>> r.cmd('afl')
'0x00000000    3 248  -> 241  sym.imp.free\n0x00003758    3 23           sym._init\n0x00003780    1 6            sym.imp.__ctype_toupper_loc\n0x00003790    1 6            s
...snipped...
```

**Comment by a1ext** [comment]
hi @securitykitten, can I ask you to test my fix? It is under testing but it seems ok.
Currently it's [here](https://github.com/a1ext/radare2-r2pipe/tree/fix-issue-81) (in branch `fix-issue-81`).
to try it you have to:
- uninstall `r2pipe` from your python `pip uninstall r2pipe`
- check out repo `git clone https://github.com/a1ext/radare2-r2pipe.git -b fix-issue-81`
- go to python implementation `cd radare2-r2pipe/python`
- install testing version `python setup.py install`
- perform your tests

P.S. Make sure you using proper python version on each step
