### ISSUE TITLE
utf8-decode! Very easy fix. 

### ISSUE THREAD

**Issue by meiraxx** [radare/radare2-r2pipe#88]
Hi guys! Please remove this decode as sometimes the output isn't utf8-decodeable. I'm referring to the file open_sync.py where I think you should remove the ".decode('utf-8')" piece of code in the _cmd_process function. thanks!

**Comment by meiraxx** [comment]
![image](https://user-images.githubusercontent.com/25626434/50499947-95937180-0a45-11e9-9607-2087a7aa73ad.png)

**Comment by radare** [comment]
Press the pencil button in github and edit the code yourself please. This will create a pullreq, which is the right place to discuss changes

**Comment by enovella** [comment]
Merged? Having similar error

```c
Warning: r_bin_file_hash: file exceeds bin.hashlimit
Traceback (most recent call last):
  File "test.py", line 114, in <module>
    main()
  File "test.py", line 104, in main
    methods = r2p.cmd("ic~)Ljava/lang/String;$")
  File "/usr/local/lib/python2.7/dist-packages/r2pipe/open_base.py", line 197, in cmd
    res = self._cmd(cmd, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/r2pipe/open_sync.py", line 125, in _cmd_process
    return out.decode('utf8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 4108-4109: invalid continuation byte
```

**Comment by enovella** [comment]
Without too much digging, I encountered some issues while manual compilation:
```c
 python] >  sudo python setup.py install
running install
running build
running build_py
running install_lib
creating /usr/local/lib/python2.7/dist-packages/r2pipe
copying build/lib.linux-x86_64-2.7/r2pipe/open_base.py -> /usr/local/lib/python2.7/dist-packages/r2pipe
copying build/lib.linux-x86_64-2.7/r2pipe/open_sync.py -> /usr/local/lib/python2.7/dist-packages/r2pipe
copying build/lib.linux-x86_64-2.7/r2pipe/__init__.py -> /usr/local/lib/python2.7/dist-packages/r2pipe
copying build/lib.linux-x86_64-2.7/r2pipe/open_async.py -> /usr/local/lib/python2.7/dist-packages/r2pipe
copying build/lib.linux-x86_64-2.7/r2pipe/native.py -> /usr/local/lib/python2.7/dist-packages/r2pipe
byte-compiling /usr/local/lib/python2.7/dist-packages/r2pipe/open_base.py to open_base.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/r2pipe/open_sync.py to open_sync.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/r2pipe/__init__.py to __init__.pyc
byte-compiling /usr/local/lib/python2.7/dist-packages/r2pipe/open_async.py to open_async.pyc
  File "/usr/local/lib/python2.7/dist-packages/r2pipe/open_async.py", line 123
    self.process = yield from create  # Init the process
                            ^
SyntaxError: invalid syntax

byte-compiling /usr/local/lib/python2.7/dist-packages/r2pipe/native.py to native.pyc
running install_egg_info
Removing /usr/local/lib/python2.7/dist-packages/r2pipe-1.2.0.egg-info
Writing /usr/local/lib/python2.7/dist-packages/r2pipe-1.2.0.egg-info
```

**Comment by enovella** [comment]
> Hi guys! Please remove this decode as sometimes the output isn't utf8-decodeable. I'm referring to the file open_sync.py where I think you should remove the ".decode('utf-8')" piece of code in the _cmd_process function. thanks!

It works!

**Comment by radare** [comment]
Provide a reproducer please

**Comment by enovella** [comment]
```c
 >  python test.py classes2.dex 
Traceback (most recent call last):
  File "test.py", line 25, in <module>
    main()
  File "test.py", line 22, in main
    methods = r2p.cmd("ic~)Ljava/lang/String;$") #.encode("utf-8")
  File "/usr/local/lib/python2.7/dist-packages/r2pipe/open_base.py", line 199, in cmd
    res = self._cmd(cmd, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/r2pipe/open_sync.py", line 125, in _cmd_process
    return out.decode('utf8')
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode bytes in position 392-393: invalid continuation byte
```
[test.zip](https://github.com/radare/radare2-r2pipe/files/3116824/test.zip)

**Comment by radare** [comment]
Ok so its not json related

**Comment by enovella** [comment]
There is a fix https://github.com/radare/radare2-r2pipe/pull/89 and I was wondering if it would be better to try-catch these 3 modified lines.
